FROM golang:1.8.3-alpine as builder
WORKDIR /go/src/
COPY app.go	.
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/app  .
CMD ["./app"]
